LOG-1075: Expose index level metrics
lukas-vlcek/elasticsearch-prometheus-exporter pull request #1
Opened 2021-07-13 03:53 UTC by sasagarw

Add index level metrics to get document count per namespace and total number of namespaces.

/cc @lukas-vlcek 

Jira: https://issues.redhat.com/browse/LOG-1075

2021-07-16 17:48 UTC, lukas-vlcek requested changes
I think this we are on a good path but there are some things that need to be changed.
I will add some commits on top of yours to address some of the issues.

2021-07-16 17:48 UTC, lukas-vlcek commented on src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java
> +                    ++totalNamespaces;
We should not be calculating number of namespaces like this. We will let Elasticsearch to do this work for us using appropriate aggregation. See my comments below please.

2021-07-16 18:14 UTC, lukas-vlcek commented on src/test/resources/rest-api-spec/test/resthandler/30_25_index_document_count.yml
> +# Test that custom metrics are getting exposed correctly
Note: I commented on this file in my original review but I assigned it to the last line of the file and it seems GitHub lost it. Ugh! The most important comment... I will re=create it here again.

1. We need (must) specify exact mapping for important/critical fields before the index is created.<br/><br/>   We can do it either by pushing in [index template](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-templates.html) or by [specifying index mapping](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-create-index.html#mappings) when the index is created explicitly.<br/><br/>   Why is this important? Because Elasticsearch will otherwise assume field types that may not be accurate for our use case. By [default](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/dynamic-field-mapping.html) `"string"` fields will be treated as [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/text.html) types. And this means that the content of the field will undergo text analysis (this is what you want to happen with full-text search engine). If not specified otherwise the content will be analyzed by [standard analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-standard-analyzer.html) which among others means that a [standard tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/analysis-standard-tokenizer.html) will be used to split the value into set of tokens. For example `"foo1"` will be broken into set of tokens `["foo", "1"]`. Just this itself means that the field will have two unique values in the index even if only a single document is indexed.<br/><br/>   In our case we need to tell Elasticsearch that the field to count the unique values on is of [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/keyword.html) type. And because right now the parsing of the response is hardcoded we need to assume data model, which defines the [`kubernetes.namespace_name` field as keyword](https://github.com/openshift/origin-aggregated-logging/blob/8de636e09f107906fcaa5bf8ac7f4ea722af24ba/elasticsearch/index_templates/com.redhat.viaq-openshift-project.template.json#L419-L424) as well (so our IT has to follow exactly the same data model structure).

2. We want to use [cardinality aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-metrics-cardinality-aggregation.html) to calculate the unique number of distinct values in some field. Using the `terms` aggregation with arbitrary high `size` value is not the way to go.

2021-07-19 04:24 UTC, sasagarw commented on src/test/resources/rest-api-spec/test/resthandler/30_25_index_document_count.yml
> +# Test that custom metrics are getting exposed correctly
Point 1 is resolved...

2021-07-19 06:19 UTC, sasagarw commented on src/test/resources/rest-api-spec/test/resthandler/30_25_index_document_count.yml
> +# Test that custom metrics are getting exposed correctly
Point 2 also done.

2021-07-29 05:29 UTC, lukas-vlcek commented
@sasagarw One suggestion that I have is this: given we currently have hardcoded logic to parse the search response I think it would be reasonable to hardcode the query as well – this means that in the first release we do not need to give user the option to configure the query at all. In other words: let's not try to find out how to make the query (non-dynamically) configurable and let's make it hardcoded. Do not even give user an option to override/change the query. The only bit that we shall give user to configure (and this will be dynamically configurable) is the option to turn on/off the processing of "custom" query. It should be off by default (and in our case I assume we will turn it on directly in `elasticsearch.yaml` configuration file) but just in case the processing flow will be expensive or start to break we will provide the option to turn it off dynamically.
I think this can be good compromise for the first release.
WDYT?

2021-07-29 05:36 UTC, sasagarw commented
> @sasagarw One suggestion that I have is this: given we currently have hardcoded logic to parse the search response I think it would be reasonable to hardcode the query as well – this means that in the first release we do not need to give user the option to configure the query at all. In other words: let's not try to find out how to make the query (non-dynamically) configurable and let's make it hardcoded. Do not even give user an option to override/change the query. The only bit that we shall give user to configure (and this will be dynamically configurable) is the option to turn on/off the processing of "custom" query. It should be off by default (and in our case I assume we will turn it on directly in `elasticsearch.yaml` configuration file) but just in case the processing flow will be expensive or start to break we will provide the option to turn it off dynamically.
> I think this can be good compromise for the first release.
> WDYT?

Yes @lukas-vlcek, I guess that would be a good way to achieve this atleast for 1st release. I will work on this today, tomorrow and update my PR. Thanks for the suggestion.

2021-07-29 07:09 UTC, lukas-vlcek commented
It will also make the IT testing possible and realistic.

2021-07-30 05:38 UTC, sasagarw commented
@lukas-vlcek can you please take a look at this once? Looks like this is what we wanted to do.

2021-08-02 13:59 UTC, lukas-vlcek commented
@sasagarw I think for the date issue in test you can use the following approach to add IT specific ingest pipeline to set a field in the document to ingestion date. That should be enough:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/accessing-data-in-pipelines.html#accessing-ingest-metadata

2021-08-02 15:39 UTC, jcantrill commented
@lukas-vlcek @sasagarw why is this PR against this repo and not the actual upstream where it needs to ultimately land?

2021-08-02 17:48 UTC, lukas-vlcek commented
@sasagarw I added one commit to workaround the date issue in unit test.

BTW, I had to switch to "full" featured ES distribution for ES tests and I think this would resolve also the issue with ingestion pipelines we had in unit tests in the past. However, I think my workaround with update API (with Painless script) requires less coding in the test.

2021-08-02 17:55 UTC, lukas-vlcek commented
@jcantrill Unfortunately, the functionality is not general enough to be offered to upstream yet. It is OCP specific only (lack of time...). But I hope we will have a chance to improve it. BTW, it is not the first time we will ship from my fork, we had to do it in the past as well.
Maybe setting up a fork in [ViaQ](https://github.com/ViaQ/) would be more appropriate ...

2021-08-04 00:17 UTC, sasagarw commented on src/main/java/org/elasticsearch/action/TransportNodePrometheusMetricsAction.java
> +                        SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
Yes, you are right. This is the most widely used working solution.

2021-08-04 07:31 UTC, lukas-vlcek commented on src/main/java/org/compuscene/metrics/prometheus/PrometheusSettings.java
> +                    Setting.Property.Dynamic, Setting.Property.NodeScope);
Outdated.

2021-08-04 07:33 UTC, lukas-vlcek commented on src/main/java/org/elasticsearch/action/TransportNodePrometheusMetricsAction.java
> +                        clusterStateResponseActionListener.onResponse(null);
@sasagarw FYI: This was a small issue.

2021-08-04 07:36 UTC, lukas-vlcek reviewed
@sasagarw Please take a look at all the changes and squash the commits. I think we can start testing this.

2021-08-04 17:46 UTC, lukas-vlcek approved these changes
/lgtm

2021-08-04 17:47 UTC, merged

2021-08-04 18:43 UTC, lukas-vlcek commented
FYI: the branch `6.8.1` was moved to branch `6.8.1.1` and then the branch `6.8.1` was deleted.